### PR TITLE
 added the modal search changed js and css

### PR DESCRIPTION
**Pull request by C-Das**
Mohammad, I saw your design for search, instead we should use a modal for search as shamoon mentioned that is a good way to get user input. This would make the search more simple. I put the jquery to copy city from DOM to the Modal page, do the mandatory validations in modal and write the warnings when mandatory values are not provided. Have a look. If you want I can merge this

### CODE REVIEW

**Comment by C-Das** [comment]
@moriz23 , I had created the pull request yesterday

**Comment by moriz23** [comment]
Okay sorry Ill take a look at it

**Comment by moriz23** [comment]
You're jquery was not working for me, I tried deleting my stuff and seeing how your code works with the page. this is partially my fault for not communicating with you and I'm sorry about that it has been a rough couple of days for me. Do you mind if we use my jquery, I completed it and it works. If you're are cool with that we will be finished with the project because I added some css and font colors for the nav and body panels. I'll then deploy it to heroku.

**Comment by C-Das** [comment]
@moriz23 , I left you a slack comm too. Please go ahead and delete this branch and push your changes to master. I'll integrate what I have done.

**Pull request closed without merging**
